# Generated by Django 5.2.15 on 2026-06-29 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Config', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_a_name', models.CharField(max_length=255)),
                ('file_b_name', models.CharField(max_length=255)),
                ('file_a_path', models.CharField(max_length=500)),
                ('file_b_path', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_records_a', models.IntegerField(default=0)),
                ('total_records_b', models.IntegerField(default=0)),
                ('matched_count', models.IntegerField(default=0)),
                ('only_a_count', models.IntegerField(default=0)),
                ('only_b_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reconcile.reconciliationconfig')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_code', models.CharField(max_length=1)),
                ('field_name', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=100)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('date', 'Date'), ('datetime', 'DateTime')], default='string', max_length=20)),
                ('is_matching_criteria', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='reconcile.reconciliationconfig')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('config', 'field_code')},
            },
        ),
        migrations.CreateModel(
            name='ReconciliationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('match', 'MATCH'), ('only_a', 'ONLY_FILE_A'), ('only_b', 'ONLY_FILE_B')], max_length=10)),
                ('file_a_data', models.JSONField(default=dict)),
                ('file_b_data', models.JSONField(default=dict)),
                ('match_key', models.CharField(db_index=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='reconcile.reconciliationsession')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'status'], name='reconcile_r_session_e0aa05_idx'), models.Index(fields=['match_key'], name='reconcile_r_match_k_d8d078_idx')],
            },
        ),
    ]
