# Generated by Django 5.2.15 on 2026-07-01 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconcile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('A', 'File A'), ('B', 'File B')], max_length=1)),
                ('excel_column', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReconciliationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('=', 'Equal')], default='=', max_length=5)),
                ('sequence', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AlterModelOptions(
            name='reconciliationconfig',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reconciliationfield',
            options={'ordering': ['sequence']},
        ),
        migrations.AlterModelOptions(
            name='reconciliationresult',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reconciliationsession',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='reconciliationresult',
            name='reconcile_r_session_e0aa05_idx',
        ),
        migrations.RemoveIndex(
            model_name='reconciliationresult',
            name='reconcile_r_match_k_d8d078_idx',
        ),
        migrations.RenameField(
            model_name='reconciliationsession',
            old_name='completed_at',
            new_name='finished_at',
        ),
        migrations.RenameField(
            model_name='reconciliationsession',
            old_name='matched_count',
            new_name='matched',
        ),
        migrations.RenameField(
            model_name='reconciliationsession',
            old_name='only_a_count',
            new_name='only_a',
        ),
        migrations.RenameField(
            model_name='reconciliationsession',
            old_name='only_b_count',
            new_name='only_b',
        ),
        migrations.RenameField(
            model_name='reconciliationsession',
            old_name='total_records_a',
            new_name='total_a',
        ),
        migrations.RenameField(
            model_name='reconciliationsession',
            old_name='total_records_b',
            new_name='total_b',
        ),
        migrations.AlterUniqueTogether(
            name='reconciliationfield',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reconciliationconfig',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reconciliationconfig',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reconciliationfield',
            name='sequence',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reconciliationresult',
            name='row_a',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reconciliationresult',
            name='row_b',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reconciliationconfig',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reconciliationfield',
            name='data_type',
            field=models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('date', 'Date')], default='string', max_length=20),
        ),
        migrations.AlterField(
            model_name='reconciliationfield',
            name='field_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reconciliationresult',
            name='match_key',
            field=models.CharField(db_index=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='reconciliationresult',
            name='status',
            field=models.CharField(choices=[('MATCH', 'MATCH'), ('ONLY_A', 'ONLY FILE A'), ('ONLY_B', 'ONLY FILE B')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reconciliationsession',
            name='file_a_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='reconciliationsession',
            name='file_b_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='fieldmapping',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='reconcile.reconciliationconfig'),
        ),
        migrations.AddField(
            model_name='fieldmapping',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reconcile.reconciliationfield'),
        ),
        migrations.AddField(
            model_name='reconciliationrule',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='reconcile.reconciliationconfig'),
        ),
        migrations.AddField(
            model_name='reconciliationrule',
            name='left_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_rules', to='reconcile.fieldmapping'),
        ),
        migrations.AddField(
            model_name='reconciliationrule',
            name='right_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_rules', to='reconcile.fieldmapping'),
        ),
        migrations.RemoveField(
            model_name='reconciliationfield',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='reconciliationfield',
            name='field_code',
        ),
        migrations.RemoveField(
            model_name='reconciliationfield',
            name='is_matching_criteria',
        ),
        migrations.RemoveField(
            model_name='reconciliationfield',
            name='order',
        ),
    ]
